### PR TITLE
Memory leaks fix and added hero image and circle cropped picture feature

### PR DESCRIPTION
**Pull request by shaovoon**
Dear Mohabouje,

I have merged my memory leaks fix and added hero image and circle cropped picture in this PR. Read about the memory leak fix in my article: https://www.codeproject.com/Articles/5286393/Cplusplus-Windows-Toast-Notification

The main memory leaks are in activatedToken, dismissedToken and failedToken which have to be removed after each callback.

There is a breaking change in showToast()'s handler parameter type which is changed from raw pointer to shared_ptr.

I want to thank you and your contributors on the behalf of all Windows programmers for writing and giving us WinToast. Thanks for this excellent library!

### CODE REVIEW

**Comment by mohabouje** [comment]
Amazing contribution! I'm a little bit busy in the coming days but I will have a look later this week and prepare a new release with the changes.

**Comment by shaovoon** [comment]
If you have any questions about my code and its rationale for doing so, please feel free to ask me here. It is faster to ask me than to figure out by yourself. I am in Singapore timezone, so I may not respond ASAP.

If there is any code that you do not agree in my implementation, I'll suggest that you merge my PR first and do the refactoring yourself rather than you and me going back and fro on how to edit my PR.

**Comment by shaovoon** [comment]
I have added SAL annotations and followed WinToast coding conventions for my code in the latest commit.

And showToast() is reverted to use IWinToastHandler raw pointer.

**Comment by shaovoon** [comment]
Dear Mohabouje,

It has been more than 2 months and this PR is still not approved. Have you reviewed the code yet?

**Comment by nickdademo** [comment]
@mohabouje Any plans to review and merge this soon?

**Comment by Paulchen-Panther** [comment]
@mohabouje It would be nice if this PR would be merged.

**Pull request merged**
