### PR TITLE
Expiration time note

### PR DESCRIPTION
**Pull request by malja**
I added short comment on expiration time method and source code example. Required in issue #29.

However after testing, expiration time affects the time notification is shown to user before moved to Action Center. I do not think this is intended. 

There are many applications with working notifications. How do they bypass this? Would you please point me to anything more I can do about this?

### CODE REVIEW

**Comment by mohabouje** [comment]
Taking a look in the [src code](https://github.com/mohabouje/WinToast/blob/cfe59a9db223e11f6f7781a799846aa47fe9ad6c/src/wintoastlib.cpp#L611) (this part was not done by myself) I see that we use the interface **ExpirationTime Property**. From the official [Microsoft documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification), I found:

_ExpirationTime Property: Gets or sets the time after which a toast notification should not be displayed._

And also:

_The date and time after which the toast is no longer considered current or valid and should not be displayed. Windows attempts to raise toast notifications immediately after you call Show, so this property is rarely used._

Another interesting fact, not sure if it's the same behavior in Windows 10 is that:

**_For Windows Phone 8.x app: this property also causes the toast notification to be removed from the action center once the specified date and time is reached._**

So, it seems that this expiration date has two usages:

- When you have a query of notifications, you can avoid the display of some of them if the expiration time is reached.

- When you show a toast, at least in Windows Phone 8.x, to remove it from the Action Center when the expiration time is reached.

I have to test both behavior. But I think that in the code we should not add this parameter if the user did not set up a valid expiration time.

By the way, I saw something strange in the code, the class MyDateTime aims to set up an expiration time by taking the current time (Now) and increasing it with the expiration time.  In this in this [line](class MyDateTime : public IReference<DateTime>).

`
_dateTime.UniversalTime = Now() + millisecondsFromNow * 10000;`

I think that the idea is to convert the msecs to microseconds or nanoseconds, so the factor is not correct. I have to check the documentation about the DateTime class.  Taking a look in to the Microsoft documentation about the [DateTime class](https://msdn.microsoft.com/es-es/library/system.datetime(v=vs.110).aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1):

**Comment by mohabouje** [comment]
UPDATE: Taking a look in to the Microsoft documentation about the [DateTime class](https://msdn.microsoft.com/es-es/library/system.datetime(v=vs.110).aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1), we have to focus in the [FILETIME](https://support.microsoft.com/en-us/help/188768/info-working-with-the-filetime-structure) structure, there we found:

**_Note that the FILETIME structure is based on 100-nanosecond intervals._**

So the conversion is correct.

**Comment by mohabouje** [comment]
You are right @malja, after testing:

_However after testing, expiration time affects the time notification is shown to user before moved to Action Center. I do not think this is intended_

This is not the normal behavour. I will work on that this week.

**Comment by malja** [comment]
@mohabouje You are right. I apologize. I did some changes to system configuration and thought it was effect of setExpiration method. 
Nevertheless, as I pointed out in #29, you still may want to allow saving notifications in Action center for each app. On my installation, it was not set by default.

**Comment by mohabouje** [comment]
@malja Definitely! Feel free to contribute. It's not something requested but it seems to be something interesting. My idea is to add some extra features that are available in modern Windows version like:

1. RemoteID:  sets a remote id for the notification that enables the system to correlate this notification with another one generated on another device.
2. Group: sets the group identifier for the notification. 
3. Tag: sets the unique identifier of this notification within the notification Group.

Then the library will give you a better way to manage/group your task.

**Pull request merged**
